### ISSUE TITLE
error in sources

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#170]
We have added a query for Sources, which is built off of consolidated notes. However, it seems that the work of consolidating all of the unique sources is not appearing. See the screenshot for example. Within the newest .bson data, consolidated_notes and parsed_notes appear to be identical. Is the problem that our data is not updated or could something else be going on? Are we missing updated data?2019-08-13.png
![2019-08-13](https://user-images.githubusercontent.com/4521013/63135660-8422b980-bf83-11e9-9cf9-906e5f4d1d5f.png)

**Comment by epicfaace** [comment]
You're probably seeing this because when @jsinge97 did the footnotes, he worked off the data from the production site. The data from the alpha site may be a bit out of sync (it was last updated when I first started working on GTE in the fall -- maybe some footnotes were removed / changed since then), so applying the same footnote scripts might not catch everything that's in alpha.

To fix, we can copy the database over from production to alpha.

After this, there's still a chance there could be a few notes that have not been consolidated properly; in that case, we will need to manually make a list of cases and then @ryanctan or I can update the database accordingly.

**Comment by ceserani** [comment]
I would love to see the actual current database in alpha
It’s hard to review as is

Sent from my iPhone

On Aug 16, 2019, at 8:27 AM, Ashwin Ramaswami <notifications@github.com<mailto:notifications@github.com>> wrote:


You're probably seeing this because when @jsinge97<https://github.com/jsinge97> did the footnotes, he worked off the data from the production site. The data from the alpha site may be a bit out of sync (it was last updated when I first started working on GTE in the fall -- maybe some footnotes were removed / changed since then), so applying the same footnote scripts might not catch everything that's in alpha.

To fix, we can copy the database over from production to alpha.

After this, there's still a chance there could be a few notes that have not been consolidated properly; in that case, we will need to manually make a list of cases and then @ryanctan<https://github.com/ryanctan> or I can update the database accordingly.
