### ISSUE TITLE
Add Entry ID Query (Lists from Book)

### ISSUE THREAD

**Issue by ryanctan** [cestastanford/grandtour#195]
Between travel date and free word search, we want another query option (similar in appearance to Dates) to paste an id or several comma-separated ids to return only those entries.

Background:
At the end of each essay, there will be an option to copy a string of ids separated by values. That will link to an Explore page where this query is performed.

**Comment by ceserani** [comment]
i have been thinking about this and wonder if one solution would be that the 'add by ID', or  maybe better name would be 'select by ID' would be an option under your results straight away and one would populate with the IDs of the lists from the essays from the book (when clicking form the book on see lists in Explorer) and have that list as results list to peruse at will, but then only be able to save it if you have a login
i imagine therefore various lists operations options visible from the start (so that any reader, regardless of having created a login or not) would see the potentials) but when you click on them saying that you need a login to save the results as a lists
this raises the question of what lists and dwld and export options will be visible from the start

**Comment by ryanctan** [comment]
No longer need for Book; list url
