### ISSUE TITLE
AND/OR/NOT: winter break task

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#2]

**Comment by quadrismegistus** [comment]
Examples queries:
* Show me all the statesmen who did **not** go to Eton
* Show me merchants who were **also** collectors (rather than merchants OR collectors)
* Show me all collectors who **never** went to Rome
* Show me all travelers who went to Venice **and** to Florence

**Comment by ceserani** [comment]
Additional examples queries

Show me all travelers who went to Venice but not to Florence 
Show me all travelers who did not go to Oxford and were statesmen

**Comment by ceserani** [comment]
Giovanna and Ryan discussed mock-ups in dec 11 meeting; Ryan will produce mock ups by Friday dec 14, discuss them with Giovanna, then submit to Ashwin by Monday 17

**Comment by quadrismegistus** [comment]
# Proposed solution to "NOT" in searches

## Example1: "Show me all the statesmen who did not go to Eton"

### Step 1: Select statesman
<img width="496" alt="q_statesmen_not_eton" src="https://user-images.githubusercontent.com/733853/50131826-e1217080-0238-11e9-87f1-02ff261c5a05.png">

### Step 2: Select Eton college
![q_statesmen_not_eton_step1](https://user-images.githubusercontent.com/733853/50131863-07dfa700-0239-11e9-9c9d-78b207583c61.png)

### Step 3: Select Eton college AGAIN to make it a negative filter
![mockup1](https://user-images.githubusercontent.com/733853/50131875-1fb72b00-0239-11e9-81f0-7c4fb21d8fa1.png)

### >> This results in the following showing on the bottom above the results
![filter_statesman_not_eton](https://user-images.githubusercontent.com/733853/50132034-de734b00-0239-11e9-8e40-db8edb5117dc.png)

**Comment by quadrismegistus** [comment]
# Proposed solution to AND/OR

## Example 2: "Show me merchants who were also collectors (rather than merchants OR collectors)"

This is an _intra-filter_ AND/OR switch.

### Step 1: Select merchant and collector
<img width="245" alt="q_collector_or_statesman" src="https://user-images.githubusercontent.com/733853/50132093-34e08980-023a-11e9-820c-25ecc7c871d4.png">

### Step 2: Go down to filter summary
![filter_statesman_or_collector](https://user-images.githubusercontent.com/733853/50132105-49248680-023a-11e9-8055-7ab9502fc0c8.png)

### Step 3: Click the "or" to make it an "and"
![filter_statesman_and_collector](https://user-images.githubusercontent.com/733853/50132113-5477b200-023a-11e9-95bd-d80b5309b8ee.png)

## Example 3: "Show me travelers who were either statesman or who went to the Royal Society"

This is an _inter-filter_ AND/OR switch.

### Step 1: Select "statesman" and "Royal Society"
<img width="505" alt="q_statesman_or_royal_society" src="https://user-images.githubusercontent.com/733853/50132169-943e9980-023a-11e9-96c6-0aef790d14b9.png">

### Step 2: Go down to filter summary
![statesman_and_royal_society](https://user-images.githubusercontent.com/733853/50132180-9c96d480-023a-11e9-9444-6adef32b2ace.png)

### Step 3: Click the "and" to make it an "or"
![statesman_or_royal_society](https://user-images.githubusercontent.com/733853/50132191-afa9a480-023a-11e9-9e17-b352942c9231.png)

## Discussion

### Objection: This doesn't resolve issues of ambiguity

One could parse "statesman and Eton or Royal Society" as either
1. "(statesman and Eton) or (Royal Society)"
2. "(statesman) and (Eton or Royal Society)"

### Solution? Assume right-branching

"statesman and Eton or Royal Society and Member of Parliament"
-> (((statesman and Eton) or Royal Society) and Member of Parliament)

The left-most statements are the deepest embedded, and so are prior in a successive, unnesting order.

**Comment by epicfaace** [comment]
Cool, can we have a call to discuss this and what we're going to accomplish over the break?

**Comment by epicfaace** [comment]
@ceserani @quadrismegistus The NOT feature is done on the alpha site now, please test it out at https://grand-tour-explorer-2017-alpha.herokuapp.com.

I need to better understand what the numbers next to each of the values means though; not sure if the logic for calculating those needs to be changed with the update for the NOT.

![image](https://user-images.githubusercontent.com/1689183/50598219-1902f780-0e78-11e9-9feb-3529ecf1ada2.png)

**Comment by ceserani** [comment]
Of the Examples queries submitted on Nov 26:

Show me all the statesmen who did not go to Eton THIS WORKS!
Show me merchants who were also collectors (rather than merchants OR collectors) not yet
Show me all collectors who never went to Rome not yet
Show me all travelers who went to Venice and to Florence not yet
