### ISSUE TITLE
Which footnotes are not possible to solve

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#4]

**Comment by ceserani** [comment]
aswhin, could you write a summary of where this item is now? ideally this write up would also serve as a sort of documentation and it would be great to have it deployed by cody to live site

**Comment by epicfaace** [comment]
Most of the existing footnotes will need to be fixed manually, such as:

Footnote.121974 is -> Footnote.<sup>12</sup> 1974 is

This is because there is no way for the computer to tell where a footnote ends and a number starts.

One feature that I have added that should make it easier is a way to manually create footnotes -- surround the number with braces. For example, the following will render correctly:

This is a footnote.{12}1974 -> This is a footnote.<sup>12</sup> 1974

The existing parsing that there is right now will still work, which works on a limited number of cases -- mainly, the case in which a sentence is followed by a period, then a number. In this case, we can leave it as it is, in which the parsing will take care of it as it is, or also (optionally) add braces.

This is a footnote.12 My next sentence. -> This is a footnote.<sup>12</sup> My next sentence.
This is a footnote.{12} My next sentence. -> This is a footnote.<sup>12</sup> My next sentence.

**Comment by ceserani** [comment]
I understand—I have a question for when we meet about this.
G

On Dec 6, 2018, at 9:31 AM, Ashwin Ramaswami <notifications@github.com<mailto:notifications@github.com>> wrote:


Most of the existing footnotes will need to be fixed manually, such as:

Footnote.121974 is -> Footnote.12 1974 is

This is because there is no way for the computer to tell where a footnote ends and a number starts.

One feature that I have added that should make it easier is a way to manually create footnotes -- surround the number with braces. For example, the following will render correctly:

This is a footnote.{12}1974 -> This is a footnote12 1974

The existing parsing that there is right now will still work, which works on a limited number of cases -- mainly, the case in which a sentence is followed by a period, then a number. In this case, we can leave it as it is, in which the parsing will take care of it as it is, or also (optionally) add braces.

This is a footnote.12 My next sentence. -> This is a footnote.12 My next sentence.
This is a footnote.{12} My next sentence. -> This is a footnote.12 My next sentence.
